#aut
version: '2'
services:
  web:
    container_name: web
    image: verchol/demochat-hpe:latest
    ports:
      - 5000
  mongo:
    image: mongo
volumes:
  output:
    external: ${{CF_VOLUME}}
      #command: sh -c 'sleep 5 && curl http://aut:5000 && echo works ? '
