version: '2'
services:
  web:
    container_name: web
    image: verchol/demochat-hpe:latest
    ports:
      - 5000:5000
  mongo:
    image: mongo

      #command: sh -c 'sleep 5 && curl http://aut:5000 && echo works ? '
